### ISSUE TITLE
The upload icons no longer work and there is are a couple of errors in console

### ISSUE THREAD

**Issue by dretelny** [StanfordHCI/foundry#250]
When you start a team and then try to click on the upload icon on the tasks, none of them work and errors appear in the console (the red gdrive button is fine though). I think this is a new issue since the gdrive/icons were working fine as of last week. Could it have been due to the tooltips or perhaps the role stuff (since one of the errors in the consoles refers to the entrymanager)? @ofagbemi and @ato1120 do you have any ideas on what is causing this? See screenshot below for console errors

![image](https://cloud.githubusercontent.com/assets/5275384/6321135/a49dfff2-baa7-11e4-8ad9-71020451f0b9.png)

**Comment by ofagbemi** [comment]
I think there might be a problem with the EntryManager there, but I think
what's causing the upload button to not work is the gdrive error. It looks
like the problem is with the new way that event ID's are assigned. The ID
is still getting treated like it's an index in an array, but since it's a
timestamp now, it's a number bigger than a trillion. This line here
<https://github.com/StanfordHCI/foundry/blob/master/app/assets/javascripts/authoring/events.js#L1348>
needs to be updated. I won't be able to get to it for probably another 7 or
so hours, but I'd fix it by just storing all the events in a hash from
their ID to the event object and writing a function to get them out of that
hash for now, since this seems pretty urgent haha.

**Comment by dretelny** [comment]
Ok! Thanks for the help! Would you mind fixing it when you can (7 hours is fine!)? 


Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by ofagbemi** [comment]
Yeah, sure!

**Comment by dretelny** [comment]
Thanks! Keep me posted :) 

Daniela Retelny
Stanford University
Department of Management Science and Engineering
(914) 450-2033
dretelny@stanford.edu <mailto:dretelny@stanford.edu>
www.danielaretelny.com <http://www.danielaretelny.com/>

**Comment by dretelny** [comment]
I actually think I figured out what the problem was and fixed it. Can you look at the changes I made and let me know if they make sense? The PR is here: https://github.com/StanfordHCI/foundry/pull/251
